"use client";
// import type { Metadata } from "next";
import "./polyfills";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "./redux/store";
import App from "./App";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
          integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body>
        <Provider store={store}>
          {/* <PersistGate persistor={persistor}> */}
          <App children={children}></App>
          {/* </PersistGate> */}
        </Provider>
      </body>
    </html>
  );
}
