"use client";
// import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import { Provider } from "react-redux";
import { store } from "./redux/store";
import App from "./App";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      {/* <PersistGate persistor={persistor}> */}
      <App children={children}></App>
      {/* </PersistGate> */}
    </Provider>
  );
}
