"use client";
// import type { Metadata } from "next";
import "bootstrap/dist/css/bootstrap.min.css";
import { Inter } from "next/font/google";
import "./globals.css";
import MMSNavbar from "./components/navbar/navbar";
import Footer from "./components/footer/footer";
import { Provider } from "react-redux";
import store from "./redux/store";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <MMSNavbar></MMSNavbar>
          </header>
          {children}
          <footer>
            <Footer></Footer>
          </footer>
        </body>
      </html>
    </Provider>
  );
}
